import { afterEach, expect, it } from 'vitest';
import { mkdtempSync, rmSync, writeFileSync, readFileSync, existsSync, mkdirSync, unlinkSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { tmpdir, hostname } from 'node:os';
import { managePortable, rollbackPortable, recoverPortableLock } from '../../src/adapters/portable-install.js';
const roots: string[] = [];
function temp() { const root = mkdtempSync(join(tmpdir(), 'omp-install-')); roots.push(root); return root; }
afterEach(() => { for (const root of roots.splice(0)) rmSync(root, { recursive: true, force: true }); });
it('dry-runs without writing; installs one complete entry and preserves workspace rules', () => {
  const root = temp(); writeFileSync(join(root, 'AGENTS.md'), 'user rules');
  const plan = managePortable(resolve('.'), root, 'codex', 'install', true) as { changes: unknown[] };
  expect(plan.changes.length).toBeGreaterThan(1); expect(existsSync(join(root, '.agents'))).toBe(false);
  managePortable(resolve('.'), root, 'codex', 'install', false);
  expect(existsSync(join(root, '.agents/skills/oh-my-patent/scripts/runtime.mjs'))).toBe(true);
  expect(readFileSync(join(root, 'AGENTS.md'), 'utf8')).toBe('user rules');
  expect(existsSync(join(root, '.codex'))).toBe(false);
});
it('retains a shared copy while another selected host still owns it', () => {
  const root = temp();
  managePortable(resolve('.'), root, 'codex', 'install', false);
  managePortable(resolve('.'), root, 'opencode', 'install', false);
  managePortable(resolve('.'), root, 'codex', 'uninstall', false);
  expect(existsSync(join(root, '.agents/skills/oh-my-patent/SKILL.md'))).toBe(true);
  managePortable(resolve('.'), root, 'opencode', 'uninstall', false);
  expect(existsSync(join(root, '.agents/skills/oh-my-patent/SKILL.md'))).toBe(false);
});
it('refuses to overwrite or uninstall user-modified package files', () => {
  const root = temp(); managePortable(resolve('.'), root, 'codex', 'install', false);
  const file = join(root, '.agents/skills/oh-my-patent/SKILL.md'); writeFileSync(file, 'user edit');
  expect(() => managePortable(resolve('.'), root, 'codex', 'install', false)).toThrow('modified');
  expect(() => managePortable(resolve('.'), root, 'codex', 'uninstall', false)).toThrow('modified');
  expect(readFileSync(file, 'utf8')).toBe('user edit');
});
it('can roll back an installation using the preserved exact-byte journal', () => {
  const root = temp();
  const result = managePortable(resolve('.'), root, 'codex', 'install', false) as { backup_id: string };
  rollbackPortable(root, result.backup_id);
  expect(existsSync(join(root, '.agents/skills/oh-my-patent/SKILL.md'))).toBe(false);
  expect(existsSync(join(root, '.oh-my-patent/installations.json'))).toBe(false);
});
it('preserves edited plugin workspace rules when adding the Skill', () => {
  const root = temp();
  // Original plugin output is outside the portable installer's ownership.
  writeFileSync(join(root, 'AGENTS.md'), '<!-- Generated by oh-my-patent. -->\nUser changes');
  const plan = managePortable(resolve('.'), root, 'codex', 'install', true) as { conflicts: string[] };
  expect(plan.conflicts).toEqual([]);
  managePortable(resolve('.'), root, 'codex', 'install', false);
  expect(readFileSync(join(root, 'AGENTS.md'), 'utf8')).toBe('<!-- Generated by oh-my-patent. -->\nUser changes');
  expect(existsSync(join(root, '.agents/skills/oh-my-patent/SKILL.md'))).toBe(true);
});
it('requires a selected host instead of defaulting to all installations', () => {
  expect(() => managePortable(resolve('.'), temp(), '', 'install', false)).toThrow('Select one host');
});
it('requires explicit rollback of a prepared installation before new changes', () => {
  const root = temp();
  const installed = managePortable(resolve('.'), root, 'codex', 'install', false) as { backup_id: string };
  const path = join(root, '.oh-my-patent/backups', installed.backup_id, 'journal.json');
  const journal = JSON.parse(readFileSync(path, 'utf8')); journal.status = 'prepared';
  writeFileSync(path, JSON.stringify(journal));
  expect(() => managePortable(resolve('.'), root, 'opencode', 'install', false)).toThrow('interrupted installation');
  rollbackPortable(root, installed.backup_id);
  managePortable(resolve('.'), root, 'codex', 'install', false);
  expect(existsSync(join(root, '.agents/skills/oh-my-patent/SKILL.md'))).toBe(true);
});
it('locks rollback and refuses to recover a live installer regardless of age', () => {
  const root = temp();
  const installed = managePortable(resolve('.'), root, 'codex', 'install', false) as { backup_id: string };
  const path = join(root, '.oh-my-patent/install.lock');
  writeFileSync(path, JSON.stringify({ token: 'live', pid: process.pid, host: hostname(), acquired_at: '2000-01-01T00:00:00Z' }));
  expect(() => rollbackPortable(root, installed.backup_id)).toThrow('locked');
  expect(() => recoverPortableLock(root, 'live')).toThrow('alive');
  unlinkSync(path);
  rollbackPortable(root, installed.backup_id);
  expect(existsSync(join(root, '.agents/skills/oh-my-patent/SKILL.md'))).toBe(false);
});
it('preserves a modified file when rolling back a completed installation', () => {
  const root = temp();
  const installed = managePortable(resolve('.'), root, 'codex', 'install', false) as { backup_id: string };
  const path = join(root, '.agents/skills/oh-my-patent/SKILL.md');
  writeFileSync(path, 'local revision');
  expect(() => rollbackPortable(root, installed.backup_id)).toThrow('User modified');
  expect(readFileSync(path, 'utf8')).toBe('local revision');
});
